### ISSUE TITLE
Change ship and landing-pad colors

### ISSUE THREAD

**Issue by PontusLindblom** [ziggyt/spel-for-samarbete-DATX02-20-90#18]
The colors are way to similar and are hard to distinguish from each other. The colors that are problematic are:
* Teal and Green
* Red and Pink

Suggested color changes:
Teal -> White
Pink -> Space grey (slightly darker grey so that we can see a difference with the white, while not being dark enough to get mixed with the blue color)

**Comment by PontusLindblom** [comment]
I would like to do this, if people are fine with the color change suggestion

**Comment by ITJohan** [comment]
Jag håller med, färgerna är väldigt lätta att ändra i ColorCoordinators colors-array. Jag har satt dem till några av Unitys inbyggda färger, men ska tydligen gå att ändra RGB värderna manuellt. Kanske sätta nån på att hitta några bra färger?

**Comment by PontusLindblom** [comment]
Har skrivit ner detta som en punkt till fredagsmötet (2020-05-08)

**Comment by PontusLindblom** [comment]
Issuet är löst genom PR #25
