### ISSUE TITLE
Create a more even light source

### ISSUE THREAD

**Issue by PontusLindblom** [ziggyt/spel-for-samarbete-DATX02-20-90#20]
Right now it seems like the light is coming from the lower right corner. This makes the color of the landing pads near that light source to look more bright, while the landing pads in the opposite corner is darker. This caused confusion and made me believe there was different versions of pink.

Solution: An even spread of the light so that the landing pads look the same.

**Comment by ITJohan** [comment]
Enkel lösning: rotera "Directional light"-objektet så det pekar rakt neråt, för den som hoppar på det. :)

**Comment by PontusLindblom** [comment]
Jag hoppar på det! Blir orimligt triggered av det obalanserade ljuset xD

**Comment by PontusLindblom** [comment]
Issuet är löst nu när PR #26 är mergad in i master
