### ISSUE TITLE
Your score is kept when you restart the game (after you die)

### ISSUE THREAD

**Issue by PontusLindblom** [ziggyt/spel-for-samarbete-DATX02-20-90#32]
De poäng man samlar ihop behålls när man starta om spelet efter att man dött.
Exempel: Mitt lag lyckas samla ihop 10 poäng innan vi dör. Vi väljer att klicka "Main Menu" och startar ett nytt spel. När spelet startas börjar vi nu med 10 poäng.

Lösning: Nollställ poängen efter att man klickar på "Main Menu"-knappen

**Comment by SpurtC** [comment]
Löst! med PR #35
