### ISSUE TITLE
The ships can't collide with the western wall

### ISSUE THREAD

**Issue by PontusLindblom** [ziggyt/spel-for-samarbete-DATX02-20-90#41]
Om ett skepp lämnar spelplanen på vänster sida, exploderar den inte som den gör på alla andra sidor (uppe, nere, höger). Den fastnar och fortsätter längs kanten O.o

**Comment by ITJohan** [comment]
Kunde inte reproducera detta. Är det samma problem i nya mastern?

**Comment by PontusLindblom** [comment]
Inte jag heller. Problemet har försvunnit någonstans på vägen :)
