### ISSUE TITLE
Make the distribusion of "clients" randome

### ISSUE THREAD

**Issue by monakilsgard** [ziggyt/spel-for-samarbete-DATX02-20-90#48]
Right now the players can select who pushes the "connect to game" button to avoid having to move the iPad in order to put together the mothership.

**Comment by ziggyt** [comment]
eventuellt så kan hur man löser #47 påverkas om man sätter spawn method till random

**Comment by ITJohan** [comment]
Om man har spawn method på random så kan vissa spelare hamn på samma kamera, så det måste lösas via kod på något sätt.
