### ISSUE TITLE
Clients should go back to main menu when host exits

### ISSUE THREAD

**Issue by ITJohan** [ziggyt/spel-for-samarbete-DATX02-20-90#54]
När hosten lämnar spelet, så servern stängs ned, så buggar klienternas kameror så de visas utanför spelplanen. Klienterna borde bli utslängda till huvudmenyn istället.

**Comment by ziggyt** [comment]
Tror jag kan lösa det här men kommer behöva ändra i kod och i samplescene

**Comment by ITJohan** [comment]
Najs, kör på!

**Comment by ziggyt** [comment]
Har hållit på med det här ett tag nu, att få den att ladda huvudmenyn gick att lösa med en custom network manager, men nu får jag konflikter med att det finns två instanser av network manager. Min custom network manager startas, men den "vanliga" network managern verkar laddas också. Eftersom den följer singleton mönstret så kallar den destroy på en utav dom, som i sin tur skapar en null reference... Ska fortsätta kika men tänkte det var nice med en uppdatering

**Comment by ITJohan** [comment]
Kanon, är ju inte hela världen om vi inte får det att fungera perfekt, men om du lyckas är det ju gött!

**Comment by ziggyt** [comment]
> 
> 
> Kanon, är ju inte hela världen om vi inte får det att fungera perfekt, men om du lyckas är det ju gött!

Håller med! Pushade upp det jag hade tillfälligt på en egen branch så att jag kan jobba på andra features så länge
