### ISSUE TITLE
Planet registrerar inte att man tar på det förrän x antal sekunder när multi touch är på

### ISSUE THREAD

**Issue by ziggyt** [ziggyt/spel-for-samarbete-DATX02-20-90#8]
https://github.com/ziggyt/spel-for-samarbete-DATX02-20-90/pull/7

**Comment by ITJohan** [comment]
Jag har prövat det både med Unity Remote 5 och att installera det direkt i min Android-telefon och det ser ut att fungera. Du är säker på att det inte bara är svårt att få tag på skeppen eftersom colliders är så små? Blir det samma sak varje gång liksom?

**Comment by ziggyt** [comment]
Alltså det var verkligen omöjligt att få tag på skeppet men jag startade om det igen och provade nyss och det verkar funka direkt. Kan ha varit att jag hade riktigt dålig accuracy igår ¯\_(ツ)_/¯
